### ISSUE TITLE
Bad Actor

### ISSUE THREAD

**Issue by Michaelzag** [Transparent-Metrics/pulse-community#1]
https://www.pulsemcp.com/servers/mcpx

**Comment by tadasant** [comment]
We exchanged emails, but pulling my explanation here for anyone reading publicly --

Thanks for the heads up! We review every submission manually, and we actually deliberately approved mcpx / mcp.run and do like what they're trying to do. In some ways their work is similar to our MCP directory within Pulse, but I expect we'll diverge over time. We hope many of the solutions across our nascent MCP community pick up traction; a rising tide lifts all boats.

I appreciate the heads up though! Good looking out.
